{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "bf7826a5_db534f25",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 1002135
      },
      "writtenOn": "2025-07-28T01:25:51Z",
      "side": 1,
      "message": "Hi all, we are encountering unknown CI failure, so I just opened it anyways for review, would be appreciated if anyone can tells the reason of the failure.",
      "revId": "44e66844e1d38fa9afe2e13f2993ceb03f3dcee5",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    }
  ],
  "submitRequirementResults": []
}