{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "bf051f66_7e696c67",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 11
      },
      "lineNbr": 0,
      "author": {
        "id": 1002135
      },
      "writtenOn": "2025-07-28T01:26:34Z",
      "side": 1,
      "message": "Hi all, we are encountering unknown CI failure, so I just opened it anyways for review, would be appreciated if anyone can tells the reason of the failure.",
      "revId": "8e1dc9a55a2bc1f7be0e6df8d7e9171cbe4ec208",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    }
  ]
}