{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "2f916651_6701036e",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 7
      },
      "lineNbr": 0,
      "author": {
        "id": 1002135
      },
      "writtenOn": "2025-07-28T01:52:52Z",
      "side": 1,
      "message": "Hi all, we are encountering an unknown CI failure, so I just opened it anyways for reviewing, would be appreciated if anyone can tell the reason of the failure.",
      "revId": "c439b479c4d50a5d420757de7eae50dc52336f5c",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    }
  ]
}